name: deployment

kind: pipeline


steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./vendor
    when:
      branch:
        - master
        - stage

  - name: build
    image: golang:1.14
    commands:
      - go env -w GOPROXY=https://goproxy.cn,direct
      - go mod vendor -v
      - make build_linux_amd64

  - name: deploy-code-stage
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER: deployer
      PLUGIN_TARGET: /var/www/codes/docker/sites/trading-central-playlists
    settings:
      hosts:
        - 172.16.11.15
      source: ./
      include:
        - "**.*"
      exclude:
        - "app.*.yml"
      script:
        - cd /var/www/codes/docker/sites/trading-central-playlists
        - ls -lah
        - echo "rebuild docker image"
        - docker-compose build app
        - echo "reload docker-compose containers"
        - docker-compose up -d
        - echo "check docker-compose status"
        - docker-compose ps
    when:
      branch:
        - stage

  - name: deploy-code-prod
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER: deployer
      PLUGIN_TARGET: /var/www/codes/avgpro.cn/trading-central-playlists
    settings:
      hosts:
        - 161.117.202.228
      source: ./
      include:
        - "**.*"
      exclude:
        - "app.*.yml"
      script:
        - cd /var/www/codes/avbpro.cn/trading-central-playlists
        - ls -lah
        - echo "rebuild docker image"
        - docker-compose build app
        - echo "reload docker-compose containers"
        - docker-compose up -d
        - echo "check docker-compose status"
        - docker-compose ps
    when:
      branch:
        - master

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./vendor
    when:
      branch:
        - stage
        - master

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
