kind: pipeline
type: docker
name: node

steps:
  - name: build
    image: golang:1.14
    commands:
      - make build_linux_amd64

  - name: build-stage
    image: plugins/docker
    commands:
      -  docker build -t docker.pkg.github.com/ava-cn/trading-central-playlists/stage:latest release/linux/amd64/trading-central-playlists

  - name: docker
    image: plugins/docker
    settings:
      registry: docker.pkg.github.com
      repo: ava-cn/trading-central-playlists/stage
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username: curder
      password:
        from_secret: github_docker_password
    commands:
      - docker push docker.pkg.github.com/ava-cn/trading-central-playlists/stage:latest
      - echo "push image to GitHub success."


