kind: pipeline
type: docker
name: node

steps:
  - name: build
    image: golang:1.14
    commands:
      - docker build -t curder/trading-central-playlists .
      - sleep 10000

  - name: docker
    image: plugins/docker
    settings:
      registry: docker.pkg.github.com
      repo: docker.pkg.github.com/ava-cn/trading-central-playlists/stage
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username: curder
      password:
        from_secret: github_docker_password


