server:
  port: 8087

database:
  driverName: mysql
  host: mysql
  port: 3306
  database: trading_central_playlists
  user: trading_central_playlists
  password: trading_central_playlists
  charset: utf8
  local: Asia/Shanghai

app:
  xml_url: https://video.tradingcentral.com/playlists/23125.xml

qiniu:
  enabled: false
  bucket: 
  privateBucket: false
  accessKey: 
  secretKey: 
  domain: 
  useHTTPS: true
  useCdnDomains: false

