---
app:
  xml_url: "https://video.tradingcentral.com/playlists/23125.xml"
database:
  charset: utf8
  database: trading_central_playlists
  driverName: mysql
  host: mysql
  local: Asia/Shanghai
  password: trading_central_playlists
  port: 3306
  user: trading_central_playlists
qiniu:
  accessKey: ~
  bucket: ~
  domain: ~
  enabled: false
  privateBucket: false
  secretKey: ~
  useCdnDomains: false
  useHTTPS: true
server:
  corsWebsites: "*"
  runMode: release
