server:
  port: 8080

database:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: trading_central_playlists
  user: root
  password:
  charset: utf8
  local: Asia/Shanghai

app:
  xml_url: https://video.tradingcentral.com/playlists/23125.xml
